// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkmRIm9ZXU1jY9E_u-6VLF_wshkkrS23Q',
    appId: '1:722274657305:web:99d6c8fae77c1ecb20f688',
    messagingSenderId: '722274657305',
    projectId: 'beitflutter',
    authDomain: 'beitflutter.firebaseapp.com',
    storageBucket: 'beitflutter.appspot.com',
    measurementId: 'G-ZV3DDLRPDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcF5ExDP-EfCqYEEiMDkPybEFmuW2hNAg',
    appId: '1:722274657305:android:88b185d42c4a4b1d20f688',
    messagingSenderId: '722274657305',
    projectId: 'beitflutter',
    storageBucket: 'beitflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-aNoT-9_rtRmuBKJRqh3j7p__tOE5Lws',
    appId: '1:722274657305:ios:49545e22cd686b4220f688',
    messagingSenderId: '722274657305',
    projectId: 'beitflutter',
    storageBucket: 'beitflutter.appspot.com',
    iosClientId: '722274657305-7nphl26n3gf7ro46vmh4rc0g1eap4782.apps.googleusercontent.com',
    iosBundleId: 'com.gsil.beitdev',
  );
}
